// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "namespace", Target = "~N:MCP2221IO")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "namespace", Target = "~N:MCP2221IO.Usb")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "namespace", Target = "~N:MCP2221IO.Gpio")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "namespace", Target = "~N:MCP2221IO.Commands")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "namespace", Target = "~N:MCP2221IO.Exceptions")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "namespace", Target = "~N:MCP2221IO.Responses")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "namespace", Target = "~N:MCP2221IO.Settings")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:MCP2221IO.Device.SramSettings")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:MCP2221IO.Device.GpioPort0")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:MCP2221IO.Device.GpioPort1")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:MCP2221IO.Device.GpioPort2")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:MCP2221IO.Device.GpioPort3")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:MCP2221IO.Device.UsbManufacturerDescriptor")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:MCP2221IO.Device.UsbProductDescriptor")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:MCP2221IO.Device.UsbSerialNumberDescriptor")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~M:MCP2221IO.Device.ReadSramSettings")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~M:MCP2221IO.Device.ReadGpioPorts")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~M:MCP2221IO.Device.WriteSramSettings(System.Boolean)")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~M:MCP2221IO.Device.WriteGpioPorts")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:MCP2221IO.DeviceStatus.AckStatus")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:MCP2221IO.DeviceStatus.SdaLineState")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:MCP2221IO.DeviceStatus.SclLineState")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~M:MCP2221IO.Responses.StatusSetParametersResponse.Deserialize(System.IO.Stream)")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~M:MCP2221IO.Responses.ReadChipSettingsResponse.Deserialize(System.IO.Stream)")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "type", Target = "~T:MCP2221IO.Exceptions.SmBusInvalidCrcException")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "type", Target = "~T:MCP2221IO.Exceptions.GpioNotEnabledException")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "type", Target = "~T:MCP2221IO.Gpio.GpioPort")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "type", Target = "~T:MCP2221IO.Settings.SramSettings")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~M:MCP2221IO.Responses.GetI2cDataResponse.Deserialize(System.IO.Stream)")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~M:MCP2221IO.Responses.ReadGpioPortsResponse.#ctor")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~M:MCP2221IO.Responses.ReadGpSettingsResponse.Deserialize(System.IO.Stream)")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:MCP2221IO.Responses.ReadGpioPortsResponse.GpioPort0")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:MCP2221IO.Responses.ReadGpioPortsResponse.GpioPort1")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:MCP2221IO.Responses.ReadGpioPortsResponse.GpioPort2")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:MCP2221IO.Responses.ReadGpioPortsResponse.GpioPort3")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~M:MCP2221IO.Responses.ReadGpioPortsResponse.Deserialize(System.IO.Stream)")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~M:MCP2221IO.Commands.WriteSramSettingsCommand.#ctor(MCP2221IO.Settings.SramSettings,System.Boolean)")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:MCP2221IO.Commands.WriteSramSettingsCommand.SramSettings")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~M:MCP2221IO.Responses.FactorySerialNumberResponse.Deserialize(System.IO.Stream)")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~M:MCP2221IO.Responses.ReadSramSettingsResponse.#ctor")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:MCP2221IO.Responses.ReadSramSettingsResponse.SramSettings")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~M:MCP2221IO.Responses.ReadSramSettingsResponse.Deserialize(System.IO.Stream)")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~M:MCP2221IO.Responses.ReadFlashStringResponse.Deserialize(System.IO.Stream)")]
